[versions]
android-gradle = "8.13.2" # make sure to update version in libs.versions.toml and buildLibs.versions.toml as well.
compose-runtime = "1.10.0"
provisioning = "0.3.3"
kotlin = "2.3.0"
material3 = "1.4.0"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"

[libraries]
adyen-provisioning = { group = "com.adyen.issuing", name = "provisioning", version.ref = "provisioning" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-runtime" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-runtime" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-runtime" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-runtime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }